name: Container Workflow

on:
  push:
    branches: [ "master" ]
permissions:
  contents: write
jobs:
  build-limarka:
    runs-on: ubuntu-latest 
    container: 
      image: docker://reinanhs/limarka:latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Run Commands
      run: |
        limarka check
        limarka --version
        limarka exec
        mkdir -p dist
        mv xxx-* ./dist/
        ls ./dist
        
    - name: Archive limarka artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-limarka
        path: dist
        retention-days: 1

  build-page:
    needs: build-limarka
    runs-on: ubuntu-latest 
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-limarka
      - shell: bash
        run: |
          ls
      - name: Run the build process with Docker
        with:
          image: reinanhs/limarka-render-html:latest
          options: -v ${{ github.workspace }}:/var/www/html/data -e APP_BASE_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
          run: |
            cd /var/www/html
            cp data/configuracao.yaml .
            mkdir -p source/assets/files/
            cp data/xxx-* source/assets/files/
            vendor/bin/jigsaw build
            mkdir -p data/build
            cp build_local/* data/build -r
      - name: Archive limarka artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-page
          path: build
          retention-days: 1
  deploy:
    needs: build-page
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build-page
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
