name: Container Workflow

on:
  push:
    branches: [ "master" ]
jobs:
#   build-limarka:
#     runs-on: ubuntu-latest 
#     container: 
#       image: docker://reinanhs/limarka:latest

#     steps:
#     - uses: actions/checkout@v3
    
#     - name: Run Commands
#       run: |
#         limarka check
#         limarka --version
#         limarka exec
#         mkdir -p dist
#         mv xxx-* ./dist/
#         ls ./dist
        
#     - name: Archive limarka artifacts
#       uses: actions/upload-artifact@v3
#       with:
#         name: dist-limarka
#         path: dist
#         retention-days: 1

  build-page:
#     needs: build-limarka
    runs-on: ubuntu-latest 
    container: 
      image: docker://reinanhs/limarka-render-html:latest
      volumes:
          - ${{ github.workspace }}:/var/www/html/
    steps:
#       - uses: actions/checkout@v3
#       - name: Download limarka artifact
#         uses: actions/download-artifact@v3
#         with:
#           name: dist-limarka
      - name: Check file
        run: ls && ls ${{ github.workspace }}
