name: Container Workflow

on:
  push:
    branches: [ "master" ]
jobs:
  build:

    runs-on: ubuntu-latest 
    container: 
      image: docker://reinanhs/limarka:latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Run Commands
      run: |
        limarka check
        limarka --version
        limarka exec
        mkdir -p dist
        mv xxx-* ./dist/
        ls ./build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-without-markdown
        path: |
          dist
